baseURL = "https://developer.elastos.org/"
languageCode = "en"
title = "Elastos developer documentation"
theme = "learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]
ignorefiles = [ "old/.*", "new/.*" ]

[params]
# Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page.
# Useful to give opportunity to people to create merge request for your doc.
# See the config.toml file from this documentation site to have an example.
editURL = "https://github.com/elastos/Elastos.Developer.Website/blob/master/content/"

# Author of the site, will be used in meta information
author = "Elastos Foundation"

# Description of the site, will be used in meta information
description = "Developers documentation for the Elastos ecosystem"

showHomeInMenu = true

# Shows a checkmark for visited pages on the menu
showVisitedLinks = false

# Disable search function. It will hide search bar
disableSearch = false

# Javascript and CSS cache are automatically busted when new version of site is generated.
# Set this to true to disable this behavior (some proxies don't handle well this optimization)
disableAssetsBusting = false

# Set this to true to disable copy-to-clipboard button for inline code.
disableInlineCopyToClipBoard = false

# A title for shortcuts in menu is set by default. Set this to true to disable it.
disableShortcutsTitle = false

# When using mulitlingual website, disable the switch language button.
disableLanguageSwitchingButton = true

# Hide breadcrumbs in the header and only show the current page title
disableBreadcrumb = false

# Hide Next and Previous page buttons normally displayed full height beside content
disableNextPrev = true

# Order sections in menu by "weight" or "title". Default to "weight"
ordersectionsby = "weight"

# Change default color scheme with a variant one. Can be "red", "blue", "green".
themeVariant = "elastos"


[languages]
[languages.en]
# contentDir = "content/english"
title = "Elastos Developer Documentation"
weight = 1
languageName = "English"

# Add a [[menu.shortcuts]] entry for each extra shortcut we want in the menu
[[languages.en.menu.shortcuts]]
name = "<i class='fab fa-github menu-shortcut-icon'></i>Elastos Github"
url = "https://github.com/elastos"
weight = 10

[[languages.en.menu.shortcuts]]
name = "<i class='fas fa-coins menu-shortcut-icon'></i>Blockchain Explorer"
url = "https://blockchain.elastos.org/"
weight = 10

[[languages.en.menu.shortcuts]]
name = "<i class='fas fa-user menu-shortcut-icon'></i>DID Blockchain Explorer"
url = "https://idchain.elastos.org/"
weight = 20

[[languages.en.menu.shortcuts]]
name = "<i class='fas fa-user menu-shortcut-icon'></i>DID Explorer"
url = "https://explorer.elaphant.app/"
weight = 25

[[languages.en.menu.shortcuts]]
name = "<i class='fab fa-ethereum menu-shortcut-icon'></i>ETH Sidechain Explorer"
url = "https://explorer.elaeth.io/"
weight = 30

[[languages.en.menu.shortcuts]]
name = "<i class='fab fa-ethereum menu-shortcut-icon'></i>ETH Sidechain Resources (Faucet/RPC Ports)"
url = "https://elaeth.io/"
weight = 35


[[languages.en.menu.shortcuts]]
name = "<i class='fab fa-linode menu-shortcut-icon'></i> Carrier nodes statistics"
url = "http://peerjet.net/"
weight = 40


[[languages.en.menu.shortcuts]]
name = "<i class='fas fa-user-friends menu-shortcut-icon'></i> Cyber Republic DAO - Get Funded"
url = "https://www.cyberrepublic.org/"
weight = 45

[[languages.en.menu.shortcuts]]
name = "<i class='fas fa-envelope menu-shortcut-icon'></i> Contact us"
url = "mailto:contact@elastos.org"
weight = 50
